//base 64
export const ETHERSCAN_ADDRESS = [
    "MHhkZGJkMmI5MzJjNzYzYmE1YjFiN2FlM2IzNjJlYWMzZThkNDAxMjFh",
    "MHg2M2E5OTc1YmEzMWIwYjk2MjZiMzQzMDBmN2Y2MjcxNDdkZjFmNTI2",
    "MHgxOThlZjFlYzMyNWE5NmNjMzU0YzcyNjZhMDM4YmU4YjVjNTU4ZjY3",
    "MHgwNDFjOTYzOTZmZjExZDA3Y2M1MGQwOTAwMjY4Y2NjMmFkZGQyODFmODczNTVjY2UxYTRhNTM0ZDAxMmRkZTc1"
]